### ISSUE TITLE
Drop support for python 3.5; add support for python 3.10 in the tests

### ISSUE THREAD

**Issue by emdee-net** [zeronet-conservancy/zeronet-conservancy#133]
In .github/workflows/tests.yml , drop support for python 3.5; and add support for python 3.10 in the tests. I doubt anyone uses less that 3.6 much, and the default Python in Gentoo is 3.10 now. If you add a setup.py, adjust it too.

(Is there a badge you can add to the README to link to the current test results?)

**Comment by caryoscelus** [comment]
it could be used on some mobile platforms . but anyway , as far as i'm concerned , the current tests are not that useful to bother (there was at least one that was written in a way that it started to fail because of dependency upgrade)

feel free to make pull-request with those changes , though . there's definitely no sense in running tests on 3.5 these days

as for badge , the tests are failing and will be failing until someone comes and fixes them . at that point it would make sense to return/add the badge

**Comment by zeronet-legal** [comment]
There is more than just tests, but probably no one reading the source code at all. Sending pull request to this repository is not recommended and nobody did ever just two scam artist who trying to collect money with other people's work.

**Comment by caryoscelus** [comment]
i'll leave this issue hanging for a bit in case anyone wants to chip in and make a PR , but otherwise it's not going to be fixed until we have new up-to-date tests in place

**Comment by emdee-net** [comment]
That's absurd and completely nonsense- you're just pretending to  maintain a fork and are "a scammer"
https://github.com/zeronet-conservancy/zeronet-conservancy/issues/113

If you were serious about maintaining it you would enable the CI testing that is in the codebase https://github.com/zeronet-conservancy/zeronet-conservancy/blob/master/.github/workflows/tests.yml and enable the CI badges on the homepage. You are doing commits without running the tests which is unacceptable.
