### ISSUE TITLE
Wrong redirect from /raw/<domain>

### ISSUE THREAD

**Issue by Robotizing** [zeronet-conservancy/zeronet-conservancy#199]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.8.1+

#### Steps to reproduce:

Run `curl http://127.0.0.1:43110/raw/miceweb.yo`

#### Observed Results:

Redirecting to /1MiceWebdn35s6pUd3EM54uNveUJNSHsMr/index.html?

#### Expected Results:

Redirecting to /raw/1MiceWebdn35s6pUd3EM54uNveUJNSHsMr

**Comment by caryoscelus** [comment]
i'm not entirely sure what do you expect `curl` to do with a directory ? i think it's `curl`'s expected behaviour to get `index.html`

as a side note , i don't use yo-domains so i've only tried `curl http://127.0.0.1:43110/raw/1MiceWebdn35s6pUd3EM54uNveUJNSHsMr` and it printed `index.html` without redirections

**Comment by caryoscelus** [comment]
ah , i see now . tried regular `.bit` domains and it does drop `/raw/` prefix indeed

**Comment by caryoscelus** [comment]
feel free to check PR above

**Comment by Robotizing** [comment]
Yes, `/raw` is key.
It works.
