### ISSUE TITLE
Error alert on the network stats page

### ISSUE THREAD

**Issue by d47081** [zeronet-conservancy/zeronet-conservancy#230]
```
Internal error: ModuleNotFoundError("No module named 'requests'"): No module named 'requests'
UiWebsocket.py line 82 > 240 > ChartPlugin.py line 56 > SidebarPlugin.py line 706 > util/Noparallel.py line 62 > 55 > SidebarPlugin.py line 699 > 605
```

maybe related to #222

**Comment by slrslr** [comment]
IMBW, but such messages suggests application (Zeronet) is unable to find needed Python module, this time it is one named "requests". You can see it listed inside file yourZNdirectory/requirements.txt
I am installing python modules like this: cd yourZNdirectory/ && pip install -r requirements.txt
Before executing that command, you need python-pip or python3-pip package installed by your Linux package manager. If you are on Windows, check https://stackoverflow.com/questions/4750806/how-do-i-install-pip-on-windows

**Comment by caryoscelus** [comment]
`requests` dependency have been added recently in order to download "bootstrap bundle" and is also used to download geoip data (which should be merged into bundle too , really) , so you have to re-run `pip install -r requirements.txt` (as per README , i recommend to run it inside venv) (also it's run automatically if you use `start-venv.sh` script) . please let me know if any problems remain after running pip

**Comment by caryoscelus** [comment]
it's been only added in https://github.com/zeronet-conservancy/zeronet-conservancy/commit/9444e097a66f9ab12562a27231fa0ba4420f37ae , so you'd have to re-run python dependency installation step if you installed it before so not really your fault
