### ISSUE TITLE
do something better with top-right button/slider

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#53]
it's confusing to people

**Comment by d4708** [comment]
agreed, I just yesterday discovered this feature when my hand stuck on the mouse click :D

**Comment by d4708** [comment]
I think, we can use custom picture for cursor `cursor: url` that explains button features

**Comment by caryoscelus** [comment]
huh, gh-email doesn't work reliably anymore.. anyway,

> I think, we can use custom picture for cursor cursor: url that explains button features

that sounds good ;) would you try to implement it?

**Comment by d4708** [comment]
Have no ideas for right now, thinking about

**Comment by d4708** [comment]
Just added new cursor icon. As I'm not pretty experienced in the GIMP editor, created something like this one.

Violet because compatible with light/dark templates. For right now I don't how to make it better. Just a thoughts to write frame-less client from zero, just for my needs where no zero id and other extra-features needed. Just a subject for new ticket / project.

Icons created by myself, feel free to license and use it as you wish!

[fixbutton.xcf.zip](https://github.com/zeronet-conservancy/zeronet-conservancy/files/8754201/fixbutton.xcf.zip)
![fixbutton](https://user-images.githubusercontent.com/96319366/169812443-ba2106db-c8bb-4099-bf60-2ed363f041c2.png)

**Comment by d4708** [comment]
Maybe we can just add some JS events to update it with another one, 
I like js-less templates. And think that client side would be rewritten.

For me looks better, than previous one.

**Comment by d4708** [comment]
@caryoscelus If you know how to add some classes to fixbutton on slide down/left events, we can add the specified vars of icons.

**Comment by d4708** [comment]
> add some classes to fixbutton on slide down/left events

Oh, my attention, it is already implemented in the parental container :D 

in my case:
`theme-dark` > `body-sidebar` (for slide left)
`theme-dark` > `body-console` (for slide down)

**Comment by d4708** [comment]
now it looks nice for me :)

also removed commented CSS because available in the commits history.
also icon set updates attached here for the next generations.

[fixbutton-set.zip](https://github.com/zeronet-conservancy/zeronet-conservancy/files/8755819/fixbutton-set.zip)

**Comment by caryoscelus** [comment]
i think new cursors are a good improvement and this can be safely closed until we get the feedback from newcomers

**Comment by caryoscelus** [comment]
> I think, we can use custom picture for cursor cursor: url that explains button features

that sounds good ;) would you try to implement it?
