### ISSUE TITLE
dubious legality of backward relicensing non-code changes to CC-BY-SA

### ISSUE THREAD

**Issue by caryoscelus** [zeronet-conservancy/zeronet-conservancy#58]
https://github.com/HelloZeroNet/ZeroNet/pull/2496 that brought them didn't have any previous contributor consent collected . at the same time the wording is also legally ambiguous . luckily cc-by-sa 4.0 allows relicensing to gplv3 , so we may almost completely safely remove that dubious clause

thoughts?

**Comment by d4708** [comment]
Even not possible - MIT <3

I don't think that license changing is a nice idea, because the software contain relations. 
That is a hard job to make it properly. Basically github forks allow the code modifications even license not provided. I think that only new code could be licensed once and components must to stay licensed originally.

**Comment by caryoscelus** [comment]
changes (however legal or not) no longer apply to new contributions so as to not complicate things . however , new contributions are GPLv3+ rather than v3only and hopefully we can eventually migrate to v3+ across the board

other than that , all of the project is GPLv3 compatible (since CC-BY-SA 4 allows relicensing to it) so there's no huge issue in having an unknown set of contributions co-licensed as CC-BY-SA . i'm closing this as i don't see any further action to be taken now and anyone who has any thoughts on this is still welcome to discuss them here
