### ISSUE TITLE
Replace Zeromail with Zeromailx 

### ISSUE THREAD

**Issue by mahdi-ln** [zeronet-conservancy/zeronet-conservancy#64]
Replace Zeromail with Zeromailx in homepage, please
Zeromailx address:
http://127.0.0.1:43110/Mail.ZeroNetX.bit/

**Comment by caryoscelus** [comment]
i have zero trust to person running it and i don't want to direct people to potentially dangerous sites . i realize 0mail author's keys might have been gotten into the wrong hands , too , but not changing status quo is better than making things worse . if you're using zeronetmailx , nothing prevents you from finding it and using it . but removing a default PM system that has been used since forever is disrupting the network .

the most important thing is to make enough network-discovering sites onto homepage .

on another note , we're deprecating .bit domains (#23) so whatever links will be are not going not be .bit links .

long term we'll have tools to make sure sites are not maliciously updated (e.g. #65) , but also i think 0mail system is not very good and should only exist for posterity reasons

as for low limit reasons which was supposed reason to create an alternative is being solved in zeronet-conservancy by allowing people to decide those for themselves (see #54)
