### ISSUE TITLE
This site requests permission: ADMIN

### ISSUE THREAD

**Issue by slrslr** [zeronet-conservancy/zeronet-conservancy#82]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.5 r5010

### Step 2: Describe the problem:

ZeroHello site http://127.0.0.1:43110/126NXcevn1AUehWFZLTBw7FrX1crEizQdr/ asks:

> This site requests permission: ADMIN
> Modify your client's configuration and access all site (Dangerous!)
> [ Grant ]

I read that this it is risky to grant this permission. What are advantages and disadvantages of granting/not granting. Etc.

**Comment by caryoscelus** [comment]
> I read that this it is risky to grant this permission. What are advantages and disadvantages of granting/not granting. Etc.

original ZeroNet client granted ADMIN permission to the starting page and page of update by default , without asking . we decided that before settling with better solution , we'll make sure users understand that the start page uses ADMIN permissions and grants them explicitly . if you don't want it / don't trust that it's a safe site , you can clone (so that no one but you can edit it) an old zerohello and grant it ADMIN permissions and use it as dashboard/admin page

if you don't grant permission to any of admin pages , you won't be able to use features like site list and notifications , but other functionality will be still in place

**Comment by caryoscelus** [comment]
yeah , all true . PRs are welcome ;) but we're a little underhanded to handle everything with the core team
