### ISSUE TITLE
No shutdown button in ZeroHello three dots menu. File descriptor was closed in another greenlet in UiWebsocket.py line 72

### ISSUE THREAD

**Issue by slrslr** [zeronet-conservancy/zeronet-conservancy#84]
### Step 1: Please describe your environment

  * ZeroNet version: 0.7.5 r5010
  * Operating system: Linux Debian 11
  * Web browser: Firefox

### Step 2: Describe the problem:

http://127.0.0.1:43110/126NXcevn1AUehWFZLTBw7FrX1crEizQdr/ does not have under three dots menu he Shutdown option like ZeronetX has. I think that shutdown option should be there.

When i did Ctr+C to terminate task via terminal, it shown [these errors](https://privatepastebin.com/?e1a03e24a860641e#2bA7hfjcmm4D5MiH56thhwrgnTkD4x6y8UChcD9jnCNd).

**Comment by caryoscelus** [comment]
thanks for reporting . the work on admin page is undergoing , we'll try to check why it doesn't appear for you . i still see it

as for shutdown errors , it seems one of those problems of exceptions that aren't harming anything but not being caught either , but are also hard to trace where they are coming from . but we are either going to get to them or just remove the offending code eventually because of other reasons

**Comment by slrslr** [comment]
You are right. After granting ADMIN permission to Dashboard site, the Shutdown entry appear and shutdown works.
The permission request dialog can cause doubts as it is. Check: https://github.com/zeronet-conservancy/zeronet-conservancy/issues/82

**Comment by caryoscelus** [comment]
i've transferred errors on close part into a separate issue , cause we're having a lot of similar seemingly benign error messages
